"use client";

import {
  Modal,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  Button,
} from "@heroui/react";
import React from "react";

interface Props {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
}

const TermsAndConditionsModal: React.FC<Props> = ({ isOpen, onOpenChange }) => {
  return (
    <Modal
      isOpen={isOpen}
      onOpenChange={onOpenChange}
      size="3xl"
      hideCloseButton
      className="overflow-hidden max-h-[95vh] sm:max-h-[200vh]"
    >
      <ModalContent>
        {(onClose) => (
          <>
            <button
              onClick={onClose}
              className="absolute top-2 right-4 z-10 flex items-center justify-center w-8 h-8 rounded-full bg-gray-100 hover:bg-[#1E40AF]/10 active:bg-[#1E40AF]/20 transition-colors"
              aria-label="Close"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5 text-gray-600 hover:text-[#1E40AF] transition-colors"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
            <ModalHeader className="flex flex-col items-center justify-center mt-6 space-y-1">
              <div className="flex items-center justify-center w-full gap-4">
                <div className="flex-grow border-t border-gray-300" />
                <h2 className="text-xl font-semibold text-[#1E40AF] whitespace-nowrap">
                  TERMS AND CONDITIONS
                </h2>
                <div className="flex-grow border-t border-gray-300" />
              </div>
              <p className="text-xs text-gray-500">
                Updated as of August 24, 2026
              </p>
            </ModalHeader>
            <ModalBody className="text-xs text-default-700 space-y-2 leading-snug px-6 overflow-y-auto sm:overflow-visible max-h-[80vh] sm:max-h-none">
              <p>
                Welcome to Alveo Land! These Terms and Conditions govern your
                use of our platform and services, including our website,
                property listings, inquiry forms, and related digital tools. By
                accessing or using any part of our platform, you agree to comply
                with these terms. Please read them carefully.
              </p>

              <p>
                <strong>1. Acceptance of Terms:</strong> By using Alveo
                Land&apos;s platform, you agree to be bound by these terms,
                along with any applicable policies (including our Privacy
                Notice) or future amendments. If you do not agree, please
                discontinue use of our services.
              </p>

              <p>
                <strong>2. Account and Security:</strong> Users are responsible
                for maintaining the confidentiality of their account
                credentials, including those used for the Customer Reservation
                Form, appointment scheduling, and other property inquiry tools.
                Any activity that occurs under your account is your
                responsibility. Notify us immediately in case of unauthorized
                use or a suspected breach.
              </p>

              <p>
                <strong>3. Use of Platform:</strong> You agree to use the
                platform solely for legitimate property inquiry, reservation,
                and related real estate purposes, in compliance with applicable
                laws and regulations, including those enforced by the Housing
                and Land Use Regulatory Board (HLURB) and the Department of
                Human Settlements and Urban Development (DHSUD). Unauthorized
                use, data scraping, or exploitation of the platform for purposes
                unrelated to legitimate property transactions is strictly
                prohibited.
              </p>

              <p>
                <strong>4. Property Listings and Availability:</strong> Property
                details, pricing, floor plans, availability, and promotional
                offers displayed on this platform are for general reference only
                and are subject to change without prior notice. Alveo Land does
                not guarantee the continued availability of any unit, lot, or
                offer, and final terms are subject to written confirmation
                through an official reservation agreement.
              </p>

              <p>
                <strong>5. Reservation and Loan Calculator Tools:</strong> Any
                figures generated by our Loan Calculator or similar tools are
                estimates only, intended to assist in preliminary financial
                planning. They do not constitute a loan offer, pre-approval, or
                guarantee of financing terms. Actual loan amounts, interest
                rates, and monthly payments are determined solely by the
                relevant bank or financing institution upon formal application
                and approval.
              </p>

              <p>
                <strong>6. Intellectual Property:</strong> All content on this
                platform, including text, graphics, logos, floor plans,
                renderings, and other digital assets, remains the intellectual
                property of Alveo Land Corp. and/or Ayala Land, Inc.
                Unauthorized use, reproduction, or distribution of this content
                is not permitted without prior written consent.
              </p>

              <p>
                <strong>7. Modifications and Termination:</strong> Alveo Land
                reserves the right to modify, suspend, or terminate any part of
                this platform or your access to it at any time without prior
                notice. We may also update these terms periodically, and
                continued use of the platform constitutes acceptance of the
                changes.
              </p>

              <p>
                <strong>8. Limitation of Liability:</strong> Alveo Land shall
                not be held liable for any direct, indirect, incidental, or
                consequential damages arising from the use of this platform, its
                tools, or any associated content, including reliance on
                estimated figures generated by the Loan Calculator.
              </p>

              <p>
                <strong>9. Governing Law:</strong> These terms are governed by
                the laws of the Republic of the Philippines. Any disputes
                arising from the use of this platform shall be resolved in
                accordance with applicable Philippine law.
              </p>

              <p>
                <strong>10. Contact Us:</strong> For questions regarding these
                Terms and Conditions, please contact us through our Customer
                Hotline or the contact details listed on our official Alveo Land
                website.
              </p>
            </ModalBody>
            <ModalFooter></ModalFooter>
          </>
        )}
      </ModalContent>
    </Modal>
  );
};

export default TermsAndConditionsModal;
